services:
  nginx:
    image: nginx:alpine
    container_name: nginx_lb_clase3
    ports:
      - "8080:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - lb_network

  backend1:
    build: 
      context: ./backend-servers
      dockerfile: Dockerfile
    container_name: backend1
    command: python slow-app.py 8001
    networks:
      - lb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend2:
    build: 
      context: ./backend-servers
      dockerfile: Dockerfile
    container_name: backend2
    command: python slow-app.py 8002
    networks:
      - lb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend3:
    build: 
      context: ./backend-servers
      dockerfile: Dockerfile
    container_name: backend3
    command: python slow-app.py 8003
    networks:
      - lb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  nginx_logs:

networks:
  lb_network:
    driver: bridge